import os
import sys

from pyramid.paster import (
    get_appsettings,
    setup_logging)

from pyramid.scripts.common import parse_vars

from ..models import User, Session, Base, engine, Post, Tag, TypeTag

def main(argv=sys.argv):
    DBSession = Session(bind=engine)
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)
    
    user = User(name="admin", password = "12345")
    DBSession.add(user)
    DBSession.commit()
    user = User(name="user1", password = "123", fullname="User user1", info="I am first user")
    DBSession.add(user)
    DBSession.commit()
    user = User(name="K", password="qwerty12345", fullname="Kate", info="Creator")
    DBSession.add(user)
    DBSession.commit()
    temp = TypeTag(name="Type page")
    DBSession.add(temp)
    DBSession.commit()
    temp = TypeTag(name="Type product")
    DBSession.add(temp)
    DBSession.commit()
    temp = TypeTag(name="Keywords")
    DBSession.add(temp)
    DBSession.commit()
    tagS = Tag(name="Schemy", typetag_id=1)
    DBSession.add(tagS)
    DBSession.commit()
    tagMK = Tag(name="Master Class", typetag_id=1)
    DBSession.add(tagMK)
    DBSession.commit()
    tagB = Tag(name="Blog page", typetag_id=1)
    DBSession.add(tagB)
    DBSession.commit()
    tagBr = Tag(name="Bracelet", typetag_id=2)
    DBSession.add(tagBr)
    DBSession.commit()
    tagI = Tag(name="Toy", typetag_id=2)
    DBSession.add(tagI)
    DBSession.commit()
    tagK = Tag(name="Cat", typetag_id=3)
    DBSession.add(tagK)
    DBSession.commit()
    tagSo = Tag(name="Owl", typetag_id=3)
    DBSession.add(tagSo)
    DBSession.commit()
    tagT = Tag(name="Test", typetag_id=3)
    DBSession.add(tagT)
    DBSession.commit()
    temp = Post(image="im1.jpg", name="Test post", user_id=1, text="Hello", info="I test")
    DBSession.add(temp)
    DBSession.commit()
    temp = Post(image="im2.jpg", name="Test master class", user_id=1, text="Hello", info="I test")
    DBSession.add(temp)
    DBSession.commit()
    temp.tags.append(tagT)
    temp.tags.append(tagMK)
    DBSession.commit()
    temp = Post(image="im3.jpg", name="Test schemy", user_id=1, text="Hello", info="I test")
    DBSession.add(temp)
    DBSession.commit()
    temp.tags.append(tagT)
    temp.tags.append(tagS)
    DBSession.commit()
    temp = Post(image="im4.jpg", name="Test blog", user_id=1, text="Hello", info="I test")
    DBSession.add(temp)
    DBSession.commit()
    temp.tags.append(tagT)
    temp.tags.append(tagB)
    DBSession.commit()
    temp = Post(image="im5.jpg", name="Cat blog", user_id=2, text="Hello", info="I test")
    DBSession.add(temp)
    DBSession.commit()
    temp.tags.append(tagB)
    temp.tags.append(tagK)
    DBSession.commit()
    temp = Post(image="im4.jpg", name="Owl blog", user_id=2, text="Hello", info="I test")
    DBSession.add(temp)
    DBSession.commit()
    temp.tags.append(tagSo)
    temp.tags.append(tagB)
    DBSession.commit()
